### ISSUE TITLE
API for getting menus from Zomato API

### ISSUE THREAD

**Issue by pgayee694** [pgayee694/menui#3]
Write an endpoint to get menus from the Zomato API

**Comment by bbuffington1662** [comment]
menu-search
- cuisines
- establishments
- categories

menu-browse
list of restaurants with:
- name
- address
- photo
- timing
- priceRange
- rating

make lists empty if there is nothing
and make name, address, etc empty if there is nothing

**Comment by pgayee694** [comment]
resolved in #18
