### ISSUE TITLE
menu browsing page

### ISSUE THREAD

**Issue by pgayee694** [pgayee694/menui#7]
Make a page for browsing menus

**Comment by bbuffington1662** [comment]
Based on the user's location

**Comment by pgayee694** [comment]
- name of page is menu-search
- endpoint for searching will be called: menu-browse
- form just needs to pass the endpoint for searching the restaurant name, categories, establishments, cuisines; endpoint should be passed the form
- make sure the form is an html form and not a flask-wtf form

**Comment by pgayee694** [comment]
resolved in #15
